[tool.poetry]
name = "hw"
version = "0.4.0"
description = "Utility software for open source programmers"
authors = ["Steve Holden <steve@holdenweb.com>"]

packages = [
    { include = "hw", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.6 || ^3.7 || ^3.8"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
tox = "^3.13"

[build-system]
requires = ["poetry>=0.12", "setuptools", "wheel"]
build-backend = "poetry.masonry.api"
