[tool.poetry]
name = "hw"
version = "0.2.0"
description = "Utility software for open source programmers"
authors = ["Steve Holden <steve@holdenweb.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
